/*
 * This source file was generated by the Gradle 'init' task
 */
package jdemo;

public class App {
    public static void main(String[] args) {
        System.out.println("=== Demo de operaciones CRUD con Lombok ===\n");

        // Crear el repositorio
        UserRepository repo = new UserRepository();

        // CREATE - Crear usuarios usando diferentes formas
        System.out.println("--- CREATE ---");

        // Forma 1: Constructor normal
        User user1 = new User(null, "Juan Pérez", "juan@email.com",
                25, true);
        user1 = repo.create(user1);
        System.out.println("Usuario creado: " + user1);

        // Forma 2: Builder pattern (gracias a @Builder de Lombok)
        User user2 = User.builder()
                .name("María García")
                .email("maria@email.com")
                .age(30)
                .active(true)
                .build();
        user2 = repo.create(user2);
        System.out.println("Usuario creado: " + user2);

        // Forma 3: Constructor vacío + setters
        User user3 = new User();
        user3.setName("Carlos López");
        user3.setEmail("carlos@email.com");
        user3.setAge(28);
        user3.setActive(false);
        user3 = repo.create(user3);
        System.out.println("Usuario creado: " + user3);

        System.out.println("\nTotal de usuarios: " + repo.count() + "\n");

        // READ - Leer usuarios
        System.out.println("--- READ ---");

        // Buscar por ID
        repo.findById(1L).ifPresent(user -> System.out.println("Usuario con ID 1: " + user));

        // Listar todos
        System.out.println("\nTodos los usuarios:");
        repo.findAll().forEach(user -> System.out.println("  - " + user.getName() +
                " (" + user.getEmail() + ")"));

        // UPDATE - Actualizar un usuario
        System.out.println("\n--- UPDATE ---");
        User updatedUser = User.builder()
                .name("Juan Pérez Actualizado")
                .email("juan.nuevo@email.com")
                .age(26)
                .active(true)
                .build();

        if (repo.update(1L, updatedUser)) {
            System.out.println("Usuario actualizado: " +
                    repo.findById(1L).get());
        }

        // DELETE - Eliminar un usuario
        System.out.println("\n--- DELETE ---");
        if (repo.delete(2L)) {
            System.out.println("Usuario con ID 2 eliminado");
        }

        System.out.println("\nUsuarios restantes:");
        repo.findAll().forEach(user -> System.out.println("  - ID: " + user.getId() +
                ", Nombre: " + user.getName()));

        System.out.println("\nTotal final de usuarios: " +
                repo.count());
    }
}
