/*
 * This source file was generated by the Gradle 'init' task
 */
package jdemo;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertDoesNotThrow(() -> App.main(null));
    }
}
